name: Android CI

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1) 코드 체크아웃
      - uses: actions/checkout@v3

      # 2) JDK 11 설치
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      # 3) Android SDK 설치
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: "31"         # 필요 SDK 버전
          ndk: false
          tools: true

      # 4) 에뮬레이터 실행 (API 30, x86_64)
      - name: Run Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          target: default
          script: |
            # AVD가 정상 부팅될 때까지 대기
            adb wait-for-device
            adb shell input keyevent 82

      # 5) Gradle 캐시
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      # 6) 빌드 & 테스트
      - name: Build & Run Tests
        run: ./gradlew clean build connectedCheck --stacktrace
