# .github/workflows/android-ci.yml
name: Android CI

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_HOME:     /usr/local/lib/android/sdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Android SDK
        uses: actions/cache@v3
        with:
          path: ${{ env.ANDROID_SDK_ROOT }}
          key: ${{ runner.os }}-android-sdk-${{ hashFiles('**/gradle/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-android-sdk-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK components
        run: |
          # 1) cmdline-tools 경로 보정 (이미 설치된 경우 무시)
          sudo ln -sf "$ANDROID_SDK_ROOT/cmdline-tools/latest" \
                      "$ANDROID_SDK_ROOT/cmdline-tools/tools" || true

          # 2) PATH에 sdkmanager 도구 추가
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/tools/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator:$PATH"

          # 3) 라이선스 동의
          yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --licenses || true

          # 4) 필수 Android SDK 패키지 설치 (불필요한 API 31/34 제거)
          sdkmanager --sdk_root="$ANDROID_SDK_ROOT" \
            "platforms;android-35" \
            "system-images;android-35;google_apis;arm64-v8a" \
            "build-tools;35.0.0"

      - name: Launch emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          arch: arm64-v8a
          target: google_apis
          disable-animations: true
          boot-timeout-minutes: 10

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}

      - name: Build, lint & run tests
        run: |
          ./gradlew -Dsdk.dir="$ANDROID_SDK_ROOT" \
            clean build lint connectedCheck --stacktrace
