# .github/workflows/android-ci.yml
name: Android CI

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_HOME:     /usr/local/lib/android/sdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK components
        run: |
          # cmdline-tools 경로 보정
          sudo ln -s "$ANDROID_SDK_ROOT/cmdline-tools/latest" \
                   "$ANDROID_SDK_ROOT/cmdline-tools/tools" || true

          # PATH에 SDK 도구들 추가
          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator:$PATH"

          # 필수 컴포넌트 설치 (Robolectric 테스트용 SDK 34 추가)
          yes | sdkmanager \
            "platform-tools" \
            "platforms;android-35" \    # compileSdkVersion 35
            "platforms;android-31" \    # emulator API 31
            "platforms;android-34" \    # Robolectric 테스트용 SDK
            "build-tools;35.0.0" \
            "emulator" \
            "system-images;android-31;default;x86_64"

          # 라이선스 동의
          yes | sdkmanager --licenses

      - name: Run Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          target: default
          emulator-options: -no-window -no-audio -no-boot-anim
          script: adb shell input keyevent 82

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}

      - name: Build, lint & run tests
        run: |
          ./gradlew -Dsdk.dir="$ANDROID_SDK_ROOT" \
            clean build lint connectedCheck --stacktrace
