# .github/workflows/android-ci.yml
# 호스트가 지원하지 않는 가상화 조건으로 인해 CI로 에뮬레이터 테스트 불가
# 임시로 계측 테스트 건너뛰고, 로컬에서 실행

name: Android CI

on:
  push:
    branches: [ main, develop ]
  pull_request:

env:
  ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
  ANDROID_HOME:     /usr/local/lib/android/sdk

# 유닛 테스트 + Lint (에뮬레이터 불필요)
jobs:
  unit-lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - uses: gradle/gradle-build-action@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Inject EMQX CA (raw resource)
        run: |
          mkdir -p app/src/main/res/raw
          echo "${{ secrets.EMQX_CA_B64 }}" | base64 -d > app/src/main/res/raw/emqx_ca.pem

      - name: Configure SDK path
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Run Lint & Unit Tests
        run: ./gradlew --no-daemon lint testDebugUnitTest --stacktrace
